In [160]:
import requests
url = "https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-State.xlsx"
resp = requests.get(url)

filename = 'data.xlsx'

output = open(filename, 'wb')
output.write(resp.content)
output.close()

In [161]:
import pandas as pd
data = []

for i in range(0,13):
    df = pd.read_excel(filename,sheet_name=i)
    data.append(df)

In [162]:
df = data[0][["state"]]

In [163]:
#gets the second column from 2018 data on homeless totals
n = 2018
for i in range(1,len(data)):
    df[str(n)] = (list(data[i].iloc[:,2]))
    n-=1

/Users/PaulAlbilal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [164]:
# Drop stuff like Guam, Virgin Islands, PR, and Total
df = df.drop([7,11,26,41,49,55], axis=0)
df

,state,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007
0,AK,2016,1845,1940,1956,1784,1946,1913,2128,1863,1992,1646,1642
1,AL,3434,3793,4111,3970,4561,4689,5209,5558,6046,6080,5387,5452
2,AR,2712,2467,2463,2560,2936,3812,4214,3424,2762,2852,3255,3836
3,AZ,9865,8947,9707,9896,10495,10562,11302,10504,13711,14721,12488,14646
4,CA,129972,131532,118142,115738,113952,118552,120098,125128,123480,123678,136531,138986
5,CO,10857,10940,10550,9953,10028,9754,16768,15116,15482,15268,14747,14225
6,CT,3976,3388,3902,4047,4450,4448,4209,4456,4316,4605,4627,4482
8,DE,1082,994,1070,953,901,946,1008,1035,982,1130,933,1061
9,FL,31030,32190,33559,35900,41542,47862,55170,56687,57551,55599,50158,48069
10,GA,9499,10174,12909,13790,16521,16971,20516,20975,19836,20360,19095,19639
12,HI,6530,7220,7921,7620,6918,6335,6246,6188,5834,5782,6061,6070
13,IA,2749,2756,3064,3081,3122,3084,2928,3134,3014,3380,3346,2734
14,ID,2012,2037,2247,1966,2104,1781,1968,2199,2346,1939,1464,1749
15,IL,10643,10798,11590,13177,13107,13425,14144,14009,14395,14055,14724,15487
16,IN,5258,5438,5798,5863,5971,6096,6259,6196,6452,6984,7395,7358
17,KS,2216,2287,2255,2588,2783,2693,2684,2511,2024,1892,1738,2111
18,KY,3688,4025,4237,4538,5089,5245,5230,6034,6623,5999,8137,8061
19,LA,3059,3305,3994,4081,4606,5226,7772,9291,12482,12504,5481,5494
20,MA,20068,17565,19608,21135,21237,19029,17501,16664,16646,15482,14506,15127
21,MD,7144,7247,7689,8390,7856,8205,9454,10208,10845,11698,9219,9628
22,ME,2516,2280,2241,2372,2726,3016,2393,2447,2379,2444,2632,2638
23,MI,8351,9051,9316,10516,12227,11527,12592,13185,13058,14005,28248,28295
24,MN,7243,7668,7341,7546,8377,8214,7744,7495,7869,7718,7644,7323
25,MO,5883,6037,6194,6482,7282,8581,10237,8989,8122,6959,7687,6247
27,MS,1352,1472,1738,1983,2226,2403,2413,2306,2743,2797,1961,1377
28,MT,1405,1529,1418,1709,1745,1878,1833,1768,1615,1196,1417,1150
29,NC,9268,8962,9559,10685,11491,12168,13524,12896,12191,12918,12411,11802
30,ND,542,1089,923,1305,1258,2069,688,603,799,773,615,636
31,NE,2421,2501,2754,2744,3026,3145,3789,3548,3877,3718,3985,3531
32,NH,1450,1456,1366,1445,1376,1447,1496,1469,1574,1645,2019,2248
33,NJ,9398,8536,8895,10098,11671,12002,13025,14137,13737,13169,13832,17314
34,NM,2551,2482,2263,2629,2746,2819,3245,3601,3475,3475,3015,3015
35,NV,7544,7833,7398,8743,8582,7039,8497,9150,11205,11089,8726,8642
36,NY,91897,89503,86352,88250,80590,77430,69566,63445,65606,61067,61125,62601
37,OH,10249,10095,10404,11182,11823,12325,13977,13030,12569,12700,12912,11264
38,OK,3871,4199,4107,3777,4191,4408,5032,4625,5229,4838,3846,4221
39,OR,14476,13953,13238,13226,12164,13822,15828,17254,19492,17309,20653,17590
40,PA,13512,14138,15339,15421,15333,15086,14736,15096,14516,15096,15378,16220
42,RI,1101,1180,1160,1111,1190,1384,1277,1070,1282,1607,1196,1372
43,SC,3933,3916,5051,5354,5057,6544,4915,5093,4473,4473,5660,5660
44,SD,1159,943,1072,1036,885,1094,859,826,731,731,579,579
45,TN,7883,8309,8779,9123,9415,9528,9426,9113,10276,10532,9705,11210
46,TX,25310,23548,23122,23678,28495,29615,34052,36911,35121,36761,40190,39788
47,UT,2876,2852,2807,3025,3081,3277,3527,3130,3284,3795,3434,3011
48,VA,5975,6067,6268,7001,7020,7625,8424,8816,9080,8852,8469,9746
50,VT,1291,1225,1117,1523,1559,1454,1160,1144,1220,1214,954,1035
51,WA,22304,21112,20827,19419,18442,17760,20504,20439,22878,22782,21954,23379
52,WI,4907,5027,5685,6057,6055,6104,6027,5785,6333,6525,5449,5648
53,WV,1243,1309,1387,1835,2013,2240,2410,2211,2264,1667,2016,2409
54,WY,639,873,857,798,757,953,1813,1038,579,515,751,537

In [165]:
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import pandas as pd
from IPython.display import IFrame


for col in df.columns:
    df[col] = df[col].astype(str)

df['text'] = df['state']

data = [go.Choropleth(
    colorscale = scl,
    autocolorscale = True,
    locations = df['state'],
    z = df['2018'].astype(float),
    locationmode = 'USA-states',
    text = df['text'],
    marker = go.choropleth.Marker(
        line = go.choropleth.marker.Line(
            color = 'rgb(255,255,255)',
            width = 2
        )),
    colorbar = go.choropleth.ColorBar(
        title = "title goes here")
)]

layout = go.Layout(
    title = go.layout.Title(
        text = 'Homelessness by State<br>(Hover for breakdown)'
    ),
    geo = go.layout.Geo(
        scope = 'usa',
        projection = go.layout.geo.Projection(type = 'albers usa'),
        showlakes = True,
        lakecolor = 'rgb(255, 255, 255)'),
)

fig = go.Figure(data = data, layout = layout)
plot(fig, filename = 'd3-cloropleth-map')

'file:///Users/PaulAlbilal/Desktop/bootcamp2/RUTJER201901DATA3/d3-cloropleth-map.html'

In [166]:
def heatmap(year):
    for col in df.columns:
        df[col] = df[col].astype(str)

    df['text'] = df['state']

    data = [go.Choropleth(
        colorscale = scl,
        autocolorscale = True,
        locations = df['state'],
        z = df[str(year)].astype(float),
        locationmode = 'USA-states',
        text = df['text'],
        marker = go.choropleth.Marker(
            line = go.choropleth.marker.Line(
                color = 'rgb(255,255,255)',
                width = 2
            )),
        colorbar = go.choropleth.ColorBar(
            title = "title goes here")
    )]

    layout = go.Layout(
        title = go.layout.Title(
            text = str(year)+' Homelessness by State<br>(Hover for breakdown)'
        ),
        geo = go.layout.Geo(
            scope = 'usa',
            projection = go.layout.geo.Projection(type = 'albers usa'),
            showlakes = True,
            lakecolor = 'rgb(255, 255, 255)'),
    )

    fig = go.Figure(data = data, layout = layout)
    plot(fig, filename = str(year)+'-d3-cloropleth-map.html')
    IFrame(str(year)+'-d3-cloropleth-map.html', width=700, height=350)

In [167]:
for i in range(2007,2019):
    heatmap(str(i))